version: '3'

services:
    eureka-server:
        container_name: eureka-server
        build:
            context: eurekaService
            dockerfile: Dockerfile
        image: eureka-server:latest
        ports:
            - 8080:8080
        networks:
            spring-cloud-network:
               aliases:
                  - eureka-server
            
    ngnix:
       build:
         context: nginx
         dockerfile: Dockerfile          
       ports:
         - "8081:8081"
         - "8082:8082"
         - "8083:8083"         
       networks: 
        - spring-cloud-network  
        
    order-service:
        build:
            context: orderService   
            dockerfile: Dockerfile
        depends_on: 
               - eureka-server        
        image: order-service:latest
        environment:
           - SERVICE_HOSTNAME=13.38.112.16        
        deploy:
           replicas: 1        
        networks:
            spring-cloud-network:
               aliases:
                  - order-service
    product-service:
        build:
            context: productService
            dockerfile: Dockerfile
        depends_on: 
               - eureka-server             
        image: product-service:latest
        environment:
           - SERVICE_HOSTNAME=13.38.112.16         
        deploy:
           replicas: 2  
        networks:
            spring-cloud-network:
               aliases:
                  - product-service
    basket-service:
        build:
            context: basketService
            dockerfile: Dockerfile
        depends_on: 
               - eureka-server             
        image: basket-service:latest
        environment:
           - SERVICE_HOSTNAME=13.38.112.16         
        deploy:
           replicas: 1
        networks:
            spring-cloud-network:
               aliases:
                  - basket-service       
networks:
    spring-cloud-network:
        driver: bridge